In [ ]:
import numpy as np
import yfinance as yf
import pandas as pd

import cvxpy as cvx # pip install cvxpy
from sklearn.covariance import LedoitWolf

In [5]:
tickers = pd.read_html(
    'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0].Symbol.to_list()
tickers = [x.replace('.','-') for x in tickers]

In [6]:
price_bar = yf.download(tickers,'2021-1-1', auto_adjust = False)

[*********************100%***********************]  503 of 503 completed

In [7]:
price_bar.to_pickle("price_1d_20210101_20250817.pk")

In [54]:
minute_bar = yf.download(tickers,interval="1m", period='8d', auto_adjust = False)

[*********************100%***********************]  503 of 503 completed

In [58]:
minute_bar.to_pickle("price_1m_20250806_20250815.pk")

In [64]:
minute_bar.swaplevel(1,0,1)['AAPL']

Price,Adj Close,Close,High,Low,Open,Volume
Datetime,,,,,,
2025-08-06 13:30:00+00:00,206.544998,206.544998,206.589996,205.589996,205.600006,3077631.0
2025-08-06 13:31:00+00:00,207.729202,207.729202,207.750000,206.529999,206.529999,988293.0
2025-08-06 13:32:00+00:00,208.269897,208.269897,208.270004,208.089996,208.158005,971527.0
2025-08-06 13:33:00+00:00,208.080002,208.080002,208.696304,208.013107,208.249893,627420.0
2025-08-06 13:34:00+00:00,208.600006,208.600006,208.649994,207.854996,208.054993,517010.0
...,...,...,...,...,...,...
2025-08-15 19:55:00+00:00,231.460007,231.460007,231.580002,231.309998,231.429993,206075.0
2025-08-15 19:56:00+00:00,231.610001,231.610001,231.610001,231.399994,231.404999,201407.0
2025-08-15 19:57:00+00:00,231.660004,231.660004,231.770004,231.580002,231.600006,229895.0
2025-08-15 19:58:00+00:00,231.500000,231.500000,231.660004,231.470001,231.660004,333324.0
2025-08-15 19:59:00+00:00,231.649994,231.649994,231.720001,231.419998,231.500000,958179.0

In [135]:
ret = minute_bar['Adj Close'] / minute_bar['Adj Close'].shift() - 1

In [138]:
sigma_lw = LedoitWolf().fit(ret.fillna(0).values).covariance_

In [144]:
LedoitWolf().fit(ret.fillna(0)).covariance_

array([[8.90931623e-07, 2.60101333e-08, 3.03846118e-08, ...,
        1.16568569e-07, 3.79814980e-08, 4.28739952e-08],
       [2.60101333e-08, 9.69221322e-07, 1.51854617e-08, ...,
        1.37773301e-07, 3.44453549e-08, 1.04807515e-09],
       [3.03846118e-08, 1.51854617e-08, 8.42102266e-07, ...,
        6.16538692e-08, 1.60726887e-08, 2.75583176e-08],
       ...,
       [1.16568569e-07, 1.37773301e-07, 6.16538692e-08, ...,
        1.60790572e-06, 1.06061419e-07, 8.75151045e-08],
       [3.79814980e-08, 3.44453549e-08, 1.60726887e-08, ...,
        1.06061419e-07, 9.93330155e-07, 1.59142891e-09],
       [4.28739952e-08, 1.04807515e-09, 2.75583176e-08, ...,
        8.75151045e-08, 1.59142891e-09, 8.97978120e-07]])

In [146]:
corr_matrix = ret.corr()

In [147]:
import seaborn as sns
import matplotlib.pyplot as plt

In [151]:
corr_matrix

Ticker,A,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WY,WYNN,XEL,XOM,XYL,XYZ,YUM,ZBH,ZBRA,ZTS
Ticker,,,,,,,,,,,,,,,,,,,,,
A,1.000000,0.149496,0.265629,-0.143365,0.179423,0.227262,0.327793,0.101854,0.337959,0.235825,...,0.425093,0.110601,0.102696,0.218385,0.271189,0.186260,0.104838,0.338942,0.279621,0.302702
AAPL,0.149496,1.000000,0.097978,-0.220895,0.032068,0.032178,0.127156,0.075665,0.200276,0.021870,...,0.142573,0.038204,-0.039544,0.073749,0.134311,0.079854,-0.023232,0.315588,0.180792,0.005481
ABBV,0.265629,0.097978,1.000000,-0.058924,0.215427,0.149709,0.130375,0.019156,0.098912,0.159384,...,0.180540,-0.042846,0.133217,0.080764,0.117104,-0.012157,0.119841,0.211213,0.135554,0.214315
ABNB,-0.143365,-0.220895,-0.058924,1.000000,0.075139,-0.015226,0.008902,0.120476,-0.160267,-0.132414,...,-0.168499,-0.040169,0.039613,-0.170470,0.025609,0.059789,-0.034514,-0.646686,-0.120670,-0.129502
ABT,0.179423,0.032068,0.215427,0.075139,1.000000,0.127575,0.080775,0.041822,0.045170,0.029635,...,0.106856,-0.015218,0.117224,0.008413,0.055950,0.004733,0.106689,0.067185,0.028689,0.152083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYZ,0.186260,0.079854,-0.012157,0.059789,0.004733,0.080872,0.207856,0.013985,0.093381,0.107936,...,0.146524,-0.067009,0.026661,0.146080,0.147745,1.000000,-0.083446,0.053328,0.261572,0.069514
YUM,0.104838,-0.023232,0.119841,-0.034514,0.106689,0.132774,0.096796,0.010749,0.117044,0.089707,...,0.124317,0.090666,0.125145,0.023905,0.053936,-0.083446,1.000000,0.047295,-0.022824,0.105810
ZBH,0.338942,0.315588,0.211213,-0.646686,0.067185,0.140130,0.222949,0.006963,0.303547,0.260239,...,0.438213,0.202236,0.051750,0.236635,0.186706,0.053328,0.047295,1.000000,0.250621,0.242052
ZBRA,0.279621,0.180792,0.135554,-0.120670,0.028689,0.095733,0.219676,0.000465,0.235767,0.128923,...,0.287513,0.017469,0.011441,0.126749,0.114134,0.261572,-0.022824,0.250621,1.000000,0.010110
ZTS,0.302702,0.005481,0.214315,-0.129502,0.152083,0.196676,0.198533,0.025105,0.179578,0.144495,...,0.280632,0.116871,0.068897,0.164783,0.139542,0.069514,0.105810,0.242052,0.010110,1.000000

In [87]:
info = yf.Ticker('AAPL').info
info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 63,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 16520856,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 60,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 57,
   'title': 'Chief People Officer & Senior VP of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 5022182,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 60,
   'title': 'Senior Vice President of Design, Watch, & Health',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 5020737,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 52,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'title': 'Chief Operating Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1754006400,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 232.78,
 'open': 233.73,
 'dayLow': 229.36,
 'dayHigh': 234.2214,
 'regularMarketPreviousClose': 232.78,
 'regularMarketOpen': 233.73,
 'regularMarketDayLow': 229.36,
 'regularMarketDayHigh': 234.2214,
 'dividendRate': 1.04,
 'dividendYield': 0.45,
 'exDividendDate': 1754870400,
 'payoutRatio': 0.1533,
 'fiveYearAvgDividendYield': 0.55,
 'beta': 1.165,
 'trailingPE': 35.089394,
 'forwardPE': 27.868832,
 'volume': 56038657,
 'regularMarketVolume': 56038657,
 'averageVolume': 56592135,
 'averageVolume10days': 72706390,
 'averageDailyVolume10Day': 72706390,
 'bid': 231.38,
 'ask': 231.72,
 'bidSize': 4,
 'askSize': 3,
 'marketCap': 3436888195072,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 260.1,
 'priceToSalesTrailing12Months': 8.410862,
 'fiftyDayAverage': 209.5868,
 'twoHundredDayAverage': 221.05106,
 'trailingAnnualDividendRate': 1.01,
 'trailingAnnualDividendYield': 0.0043388605,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3483211923456,
 'profitMargins': 0.24295999,
 'floatShares': 14814270914,
 'sharesOutstanding': 14840399872,
 'sharesShort': 104634941,
 'sharesShortPriorMonth': 110101153,
 'sharesShortPreviousMonthDate': 1751241600,
 'dateShortInterest': 1753920000,
 'sharesPercentSharesOut': 0.0070999996,
 'heldPercentInsiders': 0.0197,
 'heldPercentInstitutions': 0.637,
 'shortRatio': 2.05,
 'shortPercentOfFloat': 0.0070999996,
 'impliedSharesOutstanding': 15318899712,
 'bookValue': 4.431,
 'priceToBook': 52.26585,
 'lastFiscalYearEnd': 1727481600,
 'nextFiscalYearEnd': 1759017600,
 'mostRecentQuarter': 1751068800,
 'earningsQuarterlyGrowth': 0.093,
 'netIncomeToCommon': 99280003072,
 'trailingEps': 6.6,
 'forwardEps': 8.31,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.524,
 'enterpriseToEbitda': 24.582,
 '52WeekChange': 0.025233507,
 'SandP52WeekChange': 0.15005577,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1754870400,
 'quoteType': 'EQUITY',
 'currentPrice': 231.59,
 'targetHighPrice': 300.0,
 'targetLowPrice': 175.0,
 'targetMeanPrice': 234.27695,
 'targetMedianPrice': 238.0,
 'recommendationMean': 1.95349,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 36,
 'totalCash': 55372001280,
 'totalCashPerShare': 3.731,
 'ebitda': 141696008192,
 'totalDebt': 101698002944,
 'quickRatio': 0.724,
 'currentRatio': 0.868,
 'totalRevenue': 408624988160,
 'debtToEquity': 154.486,
 'revenuePerShare': 27.173,
 'returnOnAssets': 0.24545999,
 'returnOnEquity': 1.49814,
 'grossProfits': 190739005440,
 'freeCashflow': 94873747456,
 'operatingCashflow': 108564996096,
 'earningsGrowth': 0.121,
 'revenueGrowth': 0.096,
 'grossMargins': 0.46678,
 'ebitdaMargins': 0.34675997,
 'operatingMargins': 0.29990998,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1755302398,
 'regularMarketTime': 1755288001,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'regularMarketChangePercent': -0.51121336,
 'regularMarketPrice': 231.59,
 'earningsTimestampEnd': 1761854400,
 'earningsCallTimestampStart': 1753995600,
 'earningsCallTimestampEnd': 1753995600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 6.6,
 'epsForward': 8.31,
 'epsCurrentYear': 7.38704,
 'priceEpsCurrentYear': 31.350851,
 'fiftyDayAverageChange': 22.00319,
 'fiftyDayAverageChangePercent': 0.10498366,
 'twoHundredDayAverageChange': 10.53894,
 'twoHundredDayAverageChangePercent': 0.0476765,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': -0.1770386,
 'postMarketPrice': 231.18,
 'postMarketChange': -0.41000366,
 'regularMarketChange': -1.1900024,
 'regularMarketDayRange': '229.36 - 234.2214',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 56592135,
 'fiftyTwoWeekLowChange': 62.37999,
 'fiftyTwoWeekLowChangePercent': 0.36865425,
 'fiftyTwoWeekRange': '169.21 - 260.1',
 'fiftyTwoWeekHighChange': -28.51001,
 'fiftyTwoWeekHighChangePercent': -0.10961172,
 'fiftyTwoWeekChangePercent': 2.5233507,
 'dividendDate': 1755129600,
 'earningsTimestamp': 1753992000,
 'earningsTimestampStart': 1761854400,
 'displayName': 'Apple',
 'trailingPegRatio': 2.0905}

In [52]:
test2 = yf.Ticker('AAPL').get_income_stmt(freq = 'quarterly')

In [75]:
pd.DataFrame(info['companyOfficers'])

,maxAge,name,age,title,yearBorn,fiscalYear,totalPay,exercisedValue,unexercisedValue
0,1,Mr. Timothy D. Cook,63.0,CEO & Director,1961.0,2024,16520856.0,0,0
1,1,Ms. Katherine L. Adams,60.0,"Senior VP, General Counsel & Secretary",1964.0,2024,5022182.0,0,0
2,1,Ms. Deirdre O'Brien,57.0,Chief People Officer & Senior VP of Retail,1967.0,2024,5022182.0,0,0
3,1,Mr. Jeffrey E. Williams,60.0,"Senior Vice President of Design, Watch, & Health",1964.0,2024,5020737.0,0,0
4,1,Mr. Kevan Parekh,52.0,Senior VP & CFO,1972.0,2024,NaN,0,0
5,1,Mr. Sabih Khan,NaN,Chief Operating Officer,NaN,2024,NaN,0,0
6,1,Mr. Chris Kondo,NaN,Senior Director of Corporate Accounting,NaN,2024,NaN,0,0
7,1,Suhasini Chandramouli,NaN,Director of Investor Relations,NaN,2024,NaN,0,0
8,1,Ms. Kristin Huguet Quayle,NaN,Vice President of Worldwide Communications,NaN,2024,NaN,0,0
9,1,Mr. Greg Joswiak,NaN,Senior Vice President of Worldwide Marketing,NaN,2024,NaN,0,0

In [76]:
pd.DataFrame(info['companyOfficers'])['exercisedValue'].sum()

0

In [74]:
tickers[0]

'MMM'

In [96]:
import collections
from datetime import datetime
def executivesalary(tickers):
    salary = collections.defaultdict(list)
    for i in range(len(tickers)):
        info = yf.Ticker(tickers[i]).info
        companyOfficers = pd.DataFrame(info['companyOfficers'])
        try:
            salary[(tickers[i], 'totalpay')] = companyOfficers['totalPay'].mean()
        except:
            salary[(tickers[i], 'totalpay')] = None
        try:
            salary[(tickers[i], 'exercisedValue')] = companyOfficers['exercisedValue'].sum()
        except:
            salary[(tickers[i], 'exercisedValue')] = None
        salary[(tickers[i], 'trailingPegRatio')] = info['trailingPegRatio']
        try:
            salary[(tickers[i], 'targetMeanPrice')] = info['targetMeanPrice']
        except:
            salary[(tickers[i], 'targetMeanPrice')] = None
        try:
            salary[(tickers[i], 'next earning call')] = datetime.fromtimestamp(info['earningsTimestampStart'])
        except:
            salary[(tickers[i], 'next earning call')] = None
        salary[(tickers[i], 'shortRatio')] = info['shortRatio']
    return salary

In [97]:
generalinfo = executivesalary(tickers)

In [116]:
test = pd.Series(generalinfo)

In [126]:
test2 = test.unstack(level = 1)

In [127]:
test2

,exercisedValue,next earning call,shortRatio,targetMeanPrice,totalpay,trailingPegRatio
A,0,2025-08-27 16:00:00,1.69,137.56667,1221720.0,1.7506
AAPL,0,2025-10-30 16:00:00,2.05,234.27695,7896489.25,2.0905
ABBV,10780874,2025-07-31 08:30:00,2.68,214.76923,4297003.333333,0.4364
ABNB,75506410,2025-11-06 15:00:00,5.6,140.4,736299.5,1.7863
ABT,9807163,2025-07-17 08:30:00,2.44,142.4848,2828483.75,None
...,...,...,...,...,...,...
XYZ,43434858,2025-11-06 15:00:00,1.55,85.42432,398332.0,1.478
YUM,7321135,2025-11-04 07:30:00,3.37,158.56522,2192271.5,2.0339
ZBH,1290310,2025-10-30 08:30:00,3.51,110.91667,1864891.0,1.3351
ZBRA,2709463,2025-10-28 08:30:00,2.33,364.66666,1922658.2,1.2346
ZTS,1889510,2025-11-03 07:30:00,2.16,190.61867,2211533.0,2.4945

In [134]:
test2['shortRatio'].sort_values()

TSLA     0.74
COIN     0.78
AMD      0.79
MOH      0.84
ELV      0.92
        ...
LYV      9.94
NWS     10.48
TPL      10.6
ERIE    11.61
APO     11.78
Name: shortRatio, Length: 503, dtype: object

In [128]:
test2.to_pickle('info_summary_20250817.pk')